version: "3.7"
services:
  web:
    image: nginx:latest
    container_name: server-file-gate-example-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.4-fpm-alpine3.15
    container_name: server-file-gate-example-php
    user: "1000:1000"
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini

  composer:
      image: composer:2.4.4
      container_name: server-file-gate-example-composer
      volumes:
        - .:/composer
      working_dir: /composer
      command: install
